"""stored files for database upload storage

Revision ID: 033c176a8020
Revises: dcdcfd7f5a53
Create Date: 2026-10-08 22:12:16.938657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033c176a8020'
down_revision = 'dcdcfd7f5a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder', sa.String(length=40), nullable=False),
    sa.Column('stored_name', sa.String(length=80), nullable=False),
    sa.Column('mime_type', sa.String(length=60), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    with op.batch_alter_table('stored_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stored_files_folder'), ['folder'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stored_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stored_files_folder'))

    op.drop_table('stored_files')
    # ### end Alembic commands ###
