"""initial schema

Revision ID: 7a0e53710914
Revises: 
Create Date: 2026-10-08 19:53:32.980608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0e53710914'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_ip_address'), ['ip_address'], unique=False)

    op.create_table('project_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('contact_email', sa.String(length=254), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sandbox_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkout_id', sa.String(length=64), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('receipt', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_id'),
    sa.UniqueConstraint('receipt')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_last_counter', sa.BigInteger(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['project_partners.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)

    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_created_at'), ['created_at'], unique=False)

    op.create_table('anomaly_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('record_type', sa.String(length=60), nullable=True),
    sa.Column('record_id', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomaly_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_flags_flag_type'), ['flag_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_flags_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=254), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('record_type', sa.String(length=60), nullable=True),
    sa.Column('record_id', sa.String(length=60), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_record_type'), ['record_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_number', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complaint_number')
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaints_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_user_id'), ['user_id'], unique=False)

    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('meeting_at', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('online_link', sa.String(length=500), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('minutes', sa.Text(), nullable=True),
    sa.Column('decisions', sa.Text(), nullable=True),
    sa.Column('follow_up_actions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_meeting_at'), ['meeting_at'], unique=False)

    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('member_number', sa.String(length=20), nullable=True),
    sa.Column('id_number', sa.String(length=40), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('profile_photo', sa.String(length=80), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('admitted_at', sa.DateTime(), nullable=True),
    sa.Column('admitted_by_id', sa.Integer(), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admitted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_number'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_member_number'), ['member_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_members_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_status'), ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sms_status', sa.String(length=20), nullable=True),
    sa.Column('email_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('organization_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('requested_cents', sa.BigInteger(), nullable=False),
    sa.Column('approved_cents', sa.BigInteger(), nullable=False),
    sa.Column('budget_cents', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('financial_review_notes', sa.Text(), nullable=True),
    sa.Column('financial_reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('financial_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('risk_assessment_notes', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_assessed_by_id', sa.Integer(), nullable=True),
    sa.Column('risk_assessed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['financial_reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['project_partners.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_assessed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    op.create_table('reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=30), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('statement_balance_cents', sa.BigInteger(), nullable=False),
    sa.Column('ledger_balance_cents', sa.BigInteger(), nullable=False),
    sa.Column('difference_cents', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reconciled_by_id', sa.Integer(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reconciled_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_by_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_user_id'), ['user_id'], unique=False)

    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('budget_cents', sa.BigInteger(), nullable=False),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('eligibility', sa.String(length=20), nullable=False),
    sa.Column('opens_at', sa.DateTime(), nullable=False),
    sa.Column('closes_at', sa.DateTime(), nullable=False),
    sa.Column('quorum_percent', sa.Integer(), nullable=False),
    sa.Column('pass_percent', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('yes_count', sa.Integer(), nullable=True),
    sa.Column('no_count', sa.Integer(), nullable=True),
    sa.Column('abstain_count', sa.Integer(), nullable=True),
    sa.Column('eligible_count', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('complaint_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_responses_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_responses_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=80), nullable=False),
    sa.Column('required_cents', sa.BigInteger(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('required_cents > 0', name='ck_contribution_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'period_label')
    )
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contributions_member_id'), ['member_id'], unique=False)

    op.create_table('distribution_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_number', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('net_distributable_cents', sa.BigInteger(), nullable=False),
    sa.Column('distributed_cents', sa.BigInteger(), nullable=False),
    sa.Column('remainder_cents', sa.BigInteger(), nullable=False),
    sa.Column('eligible_count', sa.Integer(), nullable=False),
    sa.Column('rules_snapshot', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_number')
    )
    with op.batch_alter_table('distribution_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distribution_runs_project_id'), ['project_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('vote_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('stored_name', sa.String(length=80), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=60), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_vote_id'), ['vote_id'], unique=False)

    op.create_table('id_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('stored_name', sa.String(length=80), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=60), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    with op.batch_alter_table('id_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_id_documents_member_id'), ['member_id'], unique=False)

    op.create_table('meeting_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'member_id')
    )
    with op.batch_alter_table('meeting_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_attendance_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_attendance_member_id'), ['member_id'], unique=False)

    op.create_table('project_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_milestones_project_id'), ['project_id'], unique=False)

    op.create_table('project_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_updates_project_id'), ['project_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_number', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('cash_account', sa.String(length=30), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_note', sa.String(length=255), nullable=True),
    sa.Column('is_reversal', sa.Boolean(), nullable=False),
    sa.Column('reverses_id', sa.Integer(), nullable=True),
    sa.Column('reversed_by_txn_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount_cents > 0', name='ck_txn_positive'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reversed_by_txn_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['reverses_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_txn_number'), ['txn_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_type'), ['type'], unique=False)

    op.create_table('vote_ballots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.String(length=10), nullable=False),
    sa.Column('cast_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vote_id', 'member_id')
    )
    with op.batch_alter_table('vote_ballots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_ballots_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_ballots_vote_id'), ['vote_id'], unique=False)

    op.create_table('distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dist_number', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('basis_cents', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('payer_id', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount_cents >= 0', name='ck_distribution_nonneg'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['distribution_runs.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dist_number'),
    sa.UniqueConstraint('payment_reference'),
    sa.UniqueConstraint('run_id', 'member_id')
    )
    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributions_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributions_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributions_status'), ['status'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=30), nullable=False),
    sa.Column('debit_cents', sa.BigInteger(), nullable=False),
    sa.Column('credit_cents', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('debit_cents >= 0 AND credit_cents >= 0', name='ck_ledger_nonneg'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_account'), ['account'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('provider_checkout_id', sa.String(length=100), nullable=True),
    sa.Column('provider_receipt', sa.String(length=60), nullable=True),
    sa.Column('provider_result_code', sa.String(length=20), nullable=True),
    sa.Column('provider_result_desc', sa.String(length=255), nullable=True),
    sa.Column('provider_payload', sa.Text(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('initiated_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(), nullable=True),
    sa.Column('reversal_reason', sa.String(length=255), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount_cents > 0', name='ck_payment_positive'),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('provider_checkout_id'),
    sa.UniqueConstraint('provider_receipt')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_contribution_id'), ['contribution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    op.create_table('project_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('receipt_document_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reported_by_id', sa.Integer(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('amount_cents > 0', name='ck_expense_positive'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['receipt_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_expenses_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_expenses_status'), ['status'], unique=False)

    op.create_table('project_revenues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('revenue_date', sa.Date(), nullable=False),
    sa.Column('receipt_document_id', sa.Integer(), nullable=True),
    sa.Column('cash_account', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reported_by_id', sa.Integer(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('amount_cents > 0', name='ck_revenue_positive'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['receipt_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_revenues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_revenues_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_revenues_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_revenues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_revenues_status'))
        batch_op.drop_index(batch_op.f('ix_project_revenues_project_id'))

    op.drop_table('project_revenues')
    with op.batch_alter_table('project_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_expenses_status'))
        batch_op.drop_index(batch_op.f('ix_project_expenses_project_id'))

    op.drop_table('project_expenses')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_reference'))
        batch_op.drop_index(batch_op.f('ix_payments_member_id'))
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))
        batch_op.drop_index(batch_op.f('ix_payments_contribution_id'))

    op.drop_table('payments')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_account'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distributions_status'))
        batch_op.drop_index(batch_op.f('ix_distributions_run_id'))
        batch_op.drop_index(batch_op.f('ix_distributions_project_id'))
        batch_op.drop_index(batch_op.f('ix_distributions_member_id'))

    op.drop_table('distributions')
    with op.batch_alter_table('vote_ballots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_ballots_vote_id'))
        batch_op.drop_index(batch_op.f('ix_vote_ballots_member_id'))

    op.drop_table('vote_ballots')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_txn_number'))
        batch_op.drop_index(batch_op.f('ix_transactions_reference'))
        batch_op.drop_index(batch_op.f('ix_transactions_project_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_member_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_approval_status'))

    op.drop_table('transactions')
    with op.batch_alter_table('project_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_updates_project_id'))

    op.drop_table('project_updates')
    with op.batch_alter_table('project_milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_milestones_project_id'))

    op.drop_table('project_milestones')
    with op.batch_alter_table('meeting_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_attendance_member_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_attendance_meeting_id'))

    op.drop_table('meeting_attendance')
    with op.batch_alter_table('id_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_id_documents_member_id'))

    op.drop_table('id_documents')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_vote_id'))
        batch_op.drop_index(batch_op.f('ix_documents_project_id'))
        batch_op.drop_index(batch_op.f('ix_documents_meeting_id'))

    op.drop_table('documents')
    with op.batch_alter_table('distribution_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distribution_runs_project_id'))

    op.drop_table('distribution_runs')
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contributions_member_id'))

    op.drop_table('contributions')
    with op.batch_alter_table('case_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_responses_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_case_responses_complaint_id'))

    op.drop_table('case_responses')
    op.drop_table('votes')
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_user_id'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_status'))

    op.drop_table('support_tickets')
    op.drop_table('reports')
    op.drop_table('reconciliations')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_partner_id'))
        batch_op.drop_index(batch_op.f('ix_projects_code'))

    op.drop_table('projects')
    op.drop_table('organization_settings')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_status'))
        batch_op.drop_index(batch_op.f('ix_members_phone'))
        batch_op.drop_index(batch_op.f('ix_members_member_number'))

    op.drop_table('members')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_meeting_at'))

    op.drop_table('meetings')
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_user_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_status'))

    op.drop_table('complaints')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_record_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('anomaly_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_flags_status'))
        batch_op.drop_index(batch_op.f('ix_anomaly_flags_flag_type'))

    op.drop_table('anomaly_flags')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_created_at'))

    op.drop_table('announcements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_partner_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('sandbox_charges')
    op.drop_table('roles')
    op.drop_table('project_partners')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_ip_address'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_email'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_created_at'))

    op.drop_table('login_attempts')
    # ### end Alembic commands ###
