"""yedn programs and opportunities

Revision ID: dcdcfd7f5a53
Revises: 7a0e53710914
Create Date: 2026-10-08 20:44:16.934786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcdcfd7f5a53'
down_revision = '7a0e53710914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('opportunity_type', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('how_to_apply', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('members_only', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_is_published'), ['is_published'], unique=False)

    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('application_info', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programs_is_published'), ['is_published'], unique=False)

    # ### end Alembic commands ###

    # Data step: replace the old placeholder identity with YEDN in existing databases.
    settings = sa.table("organization_settings", sa.column("key", sa.String), sa.column("value", sa.Text))
    old_names = ("Umoja Demo Investment Group", "Community Investment Group", "My Community Investment Group")
    op.execute(settings.update().where(settings.c.key == "organization_name")
               .where(settings.c.value.in_(old_names))
               .values(value="Youth Enterprise & Development Network"))
    op.execute(settings.delete().where(settings.c.key == "organization_tagline")
               .where(settings.c.value.in_(("Pooling our contributions to build together.",
                                            "DEMO SITE - all people, projects and amounts are test data.",
                                            "DEMO SITE - all people, projects and money shown here are test data."))))
    # Old placeholder demo contact details are removed; official ones are entered in Settings.
    for key, value in (("contact_email", "info@demo.org"), ("contact_phone", "+254 700 000 000"),
                       ("contact_address", "Demo House, Kericho (demo address)")):
        op.execute(settings.delete().where(settings.c.key == key).where(settings.c.value == value))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programs_is_published'))

    op.drop_table('programs')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_is_published'))
        batch_op.drop_index(batch_op.f('ix_opportunities_deadline'))

    op.drop_table('opportunities')
    # ### end Alembic commands ###
